# SPDX-FileCopyrightText: Stefan Tatschner
#
# SPDX-License-Identifier: CC0-1.0

on: [push, pull_request]

name: "Tests"
permissions: {}

jobs:
   bats:
     runs-on: ubuntu-latest
     container: debian:stable
     steps:
       - uses: actions/checkout@v3
       - name: install bats
         run: |
           apt-get update && apt-get install -y bats jq zstd git util-linux
       - name: run bats
         run: |
           bats -x -r tests
