# SPDX-FileCopyrightText: Stefan Tatschner
#
# SPDX-License-Identifier: CC0-1.0

on: [push, pull_request]

name: "Tests"
permissions: {}

jobs:
  tests:
    runs-on: ubuntu-latest
    container: debian:stable

    steps:
      - uses: actions/checkout@v4
      - name: install bats
        run: |
           apt-get update && apt-get install -y bats jq zstd git util-linux make
      - name: run bats
        run: |
           make test
